version: "3.8"

services:
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=agenda.orlwambier.com.br
      - SUBDOMAINS=wildcard,
      - VALIDATION=dns
      - DNSPLUGIN=dnsimple
      - EMAIL=nilton.a.junior@hotmail.com
      - DHLEVEL=4096
    volumes:
      - config:/config
    restart: unless-stopped
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "-s", "https://agenda.orlwambier.com.br" ]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - autoheal=true
  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes: 
  config:

